apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: docker.io/plaidcloud/docs
    #Moving up a directory so we have the context of the average src folder to build in.
    context: ../
    docker:
      dockerfile: /docs/Dockerfile_Local
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yaml
    - kubernetes/ingress.yaml
    - kubernetes/service.yaml
