apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: plaid
    plaid: docs
    release: {{ .Release.Name }}
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      name: docs
      {{- if .Values.docs.annotations }}
      annotations:
{{ .Values.docs.annotations | toYaml | indent 8 }}
      {{- end }}
      labels:
        app: plaid
        plaid: docs
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: docs
        image: {{ .Values.docs.image }}
        imagePullPolicy: {{ .Values.docs.pullPolicy }}
        {{- if .Values.devMode }}
        command: ["sphinx-autobuild", "-H", "0.0.0.0", "-p", "{{ .Values.docs.port }}", "--no-initial", "/tmp/docs/source", "/web/docs"]
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.docs.port }}
        {{- if .Values.docs.resources }}
        resources:
{{ toYaml .Values.docs.resources | indent 10 }}
        {{- end }}
        # livenessProbe:
        #   httpGet:
        #     path: /docs
        #     port: {{ .Values.docs.port }}
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        # readinessProbe:
        #   httpGet:
        #     path: /docs
        #     port: {{ .Values.docs.port }}
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
      imagePullSecrets:
      - name: {{ .Values.docs.pullSecret }}
