{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.ingress.annotations }}
  annotations:
{{ .Values.ingress.annotations | toYaml | indent 4 }}
  {{- end }}
  labels:
    app: plaid
    plaid: docs
    release: {{ .Release.Name }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    {{- if .Values.devMode  }}
    - {{ .Release.Namespace }}-api.plaidcloud.io
    {{- else }}
    {{- range $hostname := .Values.ingress.hostnames }}
    - {{ $hostname }}
    {{- end }}
    {{- end }}
    secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  rules:
  {{- if .Values.devMode }}
  - host: {{ .Release.Namespace }}-api.plaidcloud.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
  {{- else }}
  {{- range $hostname := .Values.ingress.hostnames }}
  - host: {{ $hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Release.Name }}
          servicePort: 80
  {{- end }}
  {{- end }}
{{- end }}
