apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.ingress.annotations }}
  annotations:
{{ .Values.ingress.annotations | toYaml | indent 4 }}
  {{- end }}
  labels:
    app: plaid
    plaid: docs
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      if ( $http_x_forwarded_proto != 'https' ) {
        return 307 https://$host$request_uri;
      }
spec:
  rules:
  {{- if .Values.devMode }}
  - host: {{ .Release.Namespace }}.plaidcloud.io
    http:
      paths:
      - path: /docs
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
  {{- else }}
  {{- range $hostname := .Values.ingress.hostnames }}
  - host: {{ $hostname }}
    http:
      paths:
      - path: /docs
        backend:
          serviceName: {{ $.Release.Name }}
          servicePort: 80
  {{- end }}
  {{- end }}
