apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: plaid
    plaid: docs
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.spec.port }}
    protocol: TCP
    name: http
  selector:
    plaid: docs
    release: {{ .Release.Name }}
