apiVersion: v1
kind: Service
metadata:
  name: docs
  labels:
    app: plaid
    plaid: docs  
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    plaid: docs