devMode: false

docs:
  image: gcr.io/plaidcloud-build/docs
  port: 8000
  pullPolicy: IfNotPresent
  pullSecret: gcr-key
  resources: 
    requests:
      cpu: 250m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 250Mi

ingress:
  hostnames:
  - plaidcloud.com
