devMode: false

spec:
  replicas: 1
  image: gcr.io/plaidcloud-build/docs:latest
  port: 8000
  imagePullPolicy: Always
  pullSecret: gcr-key
  annotations: {}
    # co.elastic.logs/multiline.pattern: "(ERROR|WARNING|INFO|DEBUG)"
    # co.elastic.logs/multiline.negate: "true"
    # co.elastic.logs/multiline.match: "after"
  resources: {}
    # requests:
    #   cpu: 250m
    #   memory: 100Mi
    # limits:
    #   cpu: 500m
    #   memory: 250Mi

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  hostnames:
  - plaidcloud.io
  tls: true
  tlsSecret: ingress-cert
