devMode: false

docs:
  image: gcr.io/plaidcloud-build/docs:latest
  port: 8000
  pullPolicy: IfNotPresent
  pullSecret: gcr-key
  annotations: {}
  resources: {}
    # requests:
    #   cpu: 250m
    #   memory: 100Mi
    # limits:
    #   cpu: 500m
    #   memory: 250Mi

ingress:
  annotations: {}
  hostnames:
  - plaidcloud.com
  - plaidcloud.io
  tls: true
  tlsSecret: ingress-cert
